name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Approval
      - uses: pullreminders/label-when-approved-action
        env:
          APPROVALS: 1
          ADD_LABEL:  approved 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
